<?php

if ( ! function_exists( 'lazyblocks' ) ) {
    // Define path and URL to the LZB plugin.
    $my_lzb_path = get_stylesheet_directory() . '/inc/lzb/';
    $my_lzb_url  = get_stylesheet_directory_uri() . '/inc/lzb/';
   
    // Include the LZB plugin.
    require_once $my_lzb_path . 'lazy-blocks.php';
   
    lazyblocks()->include_within( $my_lzb_url );
}

add_action( 'lzb/init', function() {

    lazyblocks()->add_block( array(
        'id' => 141,
        'title' => 'Hero',
        'icon' => '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path d="M11.99 18.54l-7.37-5.73L3 14.07l9 7 9-7-1.63-1.27-7.38 5.74zM12 16l7.36-5.73L21 9l-9-7-9 7 1.63 1.27L12 16z" /></svg>',
        'keywords' => array(
        ),
        'slug' => 'lazyblock/hero',
        'description' => '',
        'category' => 'lazyblocks',
        'category_label' => 'lazyblocks',
        'supports' => array(
            'customClassName' => true,
            'anchor' => true,
            'html' => false,
            'multiple' => true,
            'inserter' => true,
            'reusable' => true,
            'lock' => true,
            'align' => array(
            ),
        ),
        'ghostkit' => array(
            'supports' => array(
                'spacings' => false,
                'display' => false,
                'scrollReveal' => false,
                'frame' => false,
                'customCSS' => false,
            ),
        ),
        'controls' => array(
            'control_746a664aaa' => array(
                'type' => 'rich_text',
                'name' => 'tagline',
                'default' => '',
                'label' => 'Tagline',
                'help' => '',
                'child_of' => '',
                'placement' => 'content',
                'width' => '100',
                'hide_if_not_selected' => 'false',
                'required' => 'false',
                'translate' => 'false',
                'save_in_meta' => 'false',
                'save_in_meta_name' => '',
                'multiline' => 'false',
                'placeholder' => '',
                'characters_limit' => '',
            ),
            'control_54ea3f4070' => array(
                'type' => 'rich_text',
                'name' => 'title',
                'default' => '',
                'label' => 'Title',
                'help' => '',
                'child_of' => '',
                'placement' => 'content',
                'width' => '100',
                'hide_if_not_selected' => 'false',
                'required' => 'false',
                'translate' => 'false',
                'save_in_meta' => 'false',
                'save_in_meta_name' => '',
                'multiline' => 'false',
                'placeholder' => '',
                'characters_limit' => '',
            ),
            'control_f98a9a4698' => array(
                'type' => 'rich_text',
                'name' => 'description',
                'default' => '',
                'label' => 'Description',
                'help' => '',
                'child_of' => '',
                'placement' => 'content',
                'width' => '100',
                'hide_if_not_selected' => 'false',
                'required' => 'false',
                'translate' => 'false',
                'save_in_meta' => 'false',
                'save_in_meta_name' => '',
                'multiline' => 'false',
                'placeholder' => '',
                'characters_limit' => '',
            ),
        ),
        'code' => array(
            'output_method' => 'template',
            'editor_html' => '',
            'editor_callback' => '',
            'editor_css' => '',
            'frontend_html' => '',
            'frontend_callback' => '',
            'frontend_css' => '',
            'show_preview' => 'never',
            'single_output' => false,
        ),
        'styles' => array(
        ),
        'condition' => array(
        ),
    ) );
    
    lazyblocks()->add_block( array(
        'id' => 140,
        'title' => '2 cols (layering)',
        'icon' => '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path d="M11.99 18.54l-7.37-5.73L3 14.07l9 7 9-7-1.63-1.27-7.38 5.74zM12 16l7.36-5.73L21 9l-9-7-9 7 1.63 1.27L12 16z" /></svg>',
        'keywords' => array(
        ),
        'slug' => 'lazyblock/two-cols-layering',
        'description' => '',
        'category' => 'lazyblocks',
        'category_label' => 'lazyblocks',
        'supports' => array(
            'customClassName' => true,
            'anchor' => true,
            'html' => false,
            'multiple' => true,
            'inserter' => true,
            'reusable' => true,
            'lock' => true,
            'align' => array(
            ),
        ),
        'ghostkit' => array(
            'supports' => array(
                'spacings' => false,
                'display' => false,
                'scrollReveal' => false,
                'frame' => false,
                'customCSS' => false,
            ),
        ),
        'controls' => array(
            'control_54ea3f4070' => array(
                'type' => 'rich_text',
                'name' => 'title',
                'default' => '',
                'label' => 'Title',
                'help' => '',
                'child_of' => '',
                'placement' => 'content',
                'width' => '100',
                'hide_if_not_selected' => 'false',
                'required' => 'false',
                'translate' => 'false',
                'save_in_meta' => 'false',
                'save_in_meta_name' => '',
                'multiline' => 'false',
                'placeholder' => '',
                'characters_limit' => '',
            ),
            'control_f98a9a4698' => array(
                'type' => 'image',
                'name' => 'image',
                'default' => '',
                'label' => 'Image',
                'help' => '',
                'child_of' => '',
                'placement' => 'content',
                'width' => '100',
                'hide_if_not_selected' => 'false',
                'required' => 'false',
                'translate' => 'false',
                'save_in_meta' => 'false',
                'save_in_meta_name' => '',
                'insert_from_url' => 'false',
                'preview_size' => 'medium',
                'placeholder' => '',
                'characters_limit' => '',
            ),
            'control_046ae24ea4' => array(
                'type' => 'rich_text',
                'name' => 'subtitle',
                'default' => '',
                'label' => 'Subtitle',
                'help' => '',
                'child_of' => '',
                'placement' => 'content',
                'width' => '100',
                'hide_if_not_selected' => 'false',
                'required' => 'false',
                'translate' => 'false',
                'save_in_meta' => 'false',
                'save_in_meta_name' => '',
                'multiline' => 'false',
                'placeholder' => '',
                'characters_limit' => '',
            ),
            'control_04985c4913' => array(
                'type' => 'rich_text',
                'name' => 'description',
                'default' => '',
                'label' => 'Description',
                'help' => '',
                'child_of' => '',
                'placement' => 'content',
                'width' => '100',
                'hide_if_not_selected' => 'false',
                'required' => 'false',
                'translate' => 'false',
                'save_in_meta' => 'false',
                'save_in_meta_name' => '',
                'multiline' => 'false',
                'placeholder' => '',
                'characters_limit' => '',
            ),
            'control_9689804570' => array(
                'type' => 'text',
                'name' => 'button',
                'default' => '',
                'label' => 'Button',
                'help' => '',
                'child_of' => '',
                'placement' => 'content',
                'width' => '50',
                'hide_if_not_selected' => 'false',
                'required' => 'false',
                'translate' => 'false',
                'save_in_meta' => 'false',
                'save_in_meta_name' => '',
                'placeholder' => '',
                'characters_limit' => '',
            ),
            'control_e8bae747af' => array(
                'type' => 'url',
                'name' => 'link',
                'default' => '',
                'label' => 'Link',
                'help' => '',
                'child_of' => '',
                'placement' => 'content',
                'width' => '50',
                'hide_if_not_selected' => 'false',
                'required' => 'false',
                'translate' => 'false',
                'save_in_meta' => 'false',
                'save_in_meta_name' => '',
                'placeholder' => '',
                'characters_limit' => '',
            ),
            'control_4a089d4d5b' => array(
                'type' => 'toggle',
                'name' => 'reverse',
                'default' => '',
                'label' => 'Reverse',
                'help' => '',
                'child_of' => '',
                'placement' => 'inspector',
                'width' => '100',
                'hide_if_not_selected' => 'false',
                'required' => 'false',
                'translate' => 'false',
                'save_in_meta' => 'false',
                'save_in_meta_name' => '',
                'checked' => 'false',
                'alongside_text' => '',
                'placeholder' => '',
                'characters_limit' => '',
            ),
            'control_9b9831488f' => array(
                'type' => 'toggle',
                'name' => 'background',
                'default' => '',
                'label' => 'Background',
                'help' => '',
                'child_of' => '',
                'placement' => 'inspector',
                'width' => '100',
                'hide_if_not_selected' => 'false',
                'required' => 'false',
                'translate' => 'false',
                'save_in_meta' => 'false',
                'save_in_meta_name' => '',
                'checked' => 'false',
                'alongside_text' => '',
                'placeholder' => '',
                'characters_limit' => '',
            ),
        ),
        'code' => array(
            'output_method' => 'template',
            'editor_html' => '',
            'editor_callback' => '',
            'editor_css' => '',
            'frontend_html' => '',
            'frontend_callback' => '',
            'frontend_css' => '',
            'show_preview' => 'never',
            'single_output' => false,
        ),
        'styles' => array(
        ),
        'condition' => array(
        ),
    ) );
    
    lazyblocks()->add_block( array(
        'id' => 139,
        'title' => 'Title + 3 cols',
        'icon' => '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path d="M11.99 18.54l-7.37-5.73L3 14.07l9 7 9-7-1.63-1.27-7.38 5.74zM12 16l7.36-5.73L21 9l-9-7-9 7 1.63 1.27L12 16z" /></svg>',
        'keywords' => array(
        ),
        'slug' => 'lazyblock/title-three-cols',
        'description' => '',
        'category' => 'lazyblocks',
        'category_label' => 'lazyblocks',
        'supports' => array(
            'customClassName' => true,
            'anchor' => true,
            'html' => false,
            'multiple' => true,
            'inserter' => true,
            'reusable' => true,
            'lock' => true,
            'align' => array(
            ),
        ),
        'ghostkit' => array(
            'supports' => array(
                'spacings' => false,
                'display' => false,
                'scrollReveal' => false,
                'frame' => false,
                'customCSS' => false,
            ),
        ),
        'controls' => array(
            'control_54ea3f4070' => array(
                'type' => 'rich_text',
                'name' => 'title',
                'default' => '',
                'label' => 'Title',
                'help' => '',
                'child_of' => '',
                'placement' => 'content',
                'width' => '100',
                'hide_if_not_selected' => 'false',
                'required' => 'false',
                'translate' => 'false',
                'save_in_meta' => 'false',
                'save_in_meta_name' => '',
                'multiline' => 'false',
                'placeholder' => '',
                'characters_limit' => '',
            ),
            'control_6fa8fc4434' => array(
                'type' => 'repeater',
                'name' => 'repeater',
                'default' => '',
                'label' => 'Repeater',
                'help' => '',
                'child_of' => '',
                'placement' => 'content',
                'width' => '100',
                'hide_if_not_selected' => 'false',
                'required' => 'false',
                'translate' => 'false',
                'save_in_meta' => 'false',
                'save_in_meta_name' => '',
                'rows_min' => '',
                'rows_max' => '',
                'rows_label' => '',
                'rows_add_button_label' => '',
                'rows_collapsible' => 'true',
                'rows_collapsed' => 'true',
                'placeholder' => '',
                'characters_limit' => '',
            ),
            'control_61cac74aff' => array(
                'type' => 'rich_text',
                'name' => 'subtitle',
                'default' => '',
                'label' => 'Subtitle',
                'help' => '',
                'child_of' => 'control_6fa8fc4434',
                'placement' => 'content',
                'width' => '100',
                'hide_if_not_selected' => 'false',
                'required' => 'false',
                'translate' => 'false',
                'save_in_meta' => 'false',
                'save_in_meta_name' => '',
                'multiline' => 'false',
                'placeholder' => '',
                'characters_limit' => '',
            ),
            'control_8ab9de43b2' => array(
                'type' => 'rich_text',
                'name' => 'description',
                'default' => '',
                'label' => 'Description',
                'help' => '',
                'child_of' => 'control_6fa8fc4434',
                'placement' => 'content',
                'width' => '100',
                'hide_if_not_selected' => 'false',
                'required' => 'false',
                'translate' => 'false',
                'save_in_meta' => 'false',
                'save_in_meta_name' => '',
                'multiline' => 'false',
                'placeholder' => '',
                'characters_limit' => '',
            ),
        ),
        'code' => array(
            'output_method' => 'template',
            'editor_html' => '',
            'editor_callback' => '',
            'editor_css' => '',
            'frontend_html' => '',
            'frontend_callback' => '',
            'frontend_css' => '',
            'show_preview' => 'never',
            'single_output' => false,
        ),
        'styles' => array(
        ),
        'condition' => array(
        ),
    ) );
    
    lazyblocks()->add_block( array(
        'id' => 138,
        'title' => 'Title + 4 cols (cards)',
        'icon' => '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path d="M11.99 18.54l-7.37-5.73L3 14.07l9 7 9-7-1.63-1.27-7.38 5.74zM12 16l7.36-5.73L21 9l-9-7-9 7 1.63 1.27L12 16z" /></svg>',
        'keywords' => array(
        ),
        'slug' => 'lazyblock/title-four-cols-cards',
        'description' => '',
        'category' => 'lazyblocks',
        'category_label' => 'lazyblocks',
        'supports' => array(
            'customClassName' => true,
            'anchor' => true,
            'html' => false,
            'multiple' => true,
            'inserter' => true,
            'reusable' => true,
            'lock' => true,
            'align' => array(
            ),
        ),
        'ghostkit' => array(
            'supports' => array(
                'spacings' => false,
                'display' => false,
                'scrollReveal' => false,
                'frame' => false,
                'customCSS' => false,
            ),
        ),
        'controls' => array(
            'control_54ea3f4070' => array(
                'type' => 'rich_text',
                'name' => 'title',
                'default' => '',
                'label' => 'Title',
                'help' => '',
                'child_of' => '',
                'placement' => 'content',
                'width' => '100',
                'hide_if_not_selected' => 'false',
                'required' => 'false',
                'translate' => 'false',
                'save_in_meta' => 'false',
                'save_in_meta_name' => '',
                'multiline' => 'false',
                'placeholder' => '',
                'characters_limit' => '',
            ),
            'control_6fa8fc4434' => array(
                'type' => 'repeater',
                'name' => 'repeater',
                'default' => '',
                'label' => 'Repeater',
                'help' => '',
                'child_of' => '',
                'placement' => 'content',
                'width' => '100',
                'hide_if_not_selected' => 'false',
                'required' => 'false',
                'translate' => 'false',
                'save_in_meta' => 'false',
                'save_in_meta_name' => '',
                'rows_min' => '',
                'rows_max' => '',
                'rows_label' => '',
                'rows_add_button_label' => '',
                'rows_collapsible' => 'true',
                'rows_collapsed' => 'true',
                'placeholder' => '',
                'characters_limit' => '',
            ),
            'control_61cac74aff' => array(
                'type' => 'rich_text',
                'name' => 'label',
                'default' => '',
                'label' => 'Label',
                'help' => '',
                'child_of' => 'control_6fa8fc4434',
                'placement' => 'content',
                'width' => '100',
                'hide_if_not_selected' => 'false',
                'required' => 'false',
                'translate' => 'false',
                'save_in_meta' => 'false',
                'save_in_meta_name' => '',
                'multiline' => 'false',
                'placeholder' => '',
                'characters_limit' => '',
            ),
            'control_8ab9de43b2' => array(
                'type' => 'rich_text',
                'name' => 'value',
                'default' => '',
                'label' => 'Value',
                'help' => '',
                'child_of' => 'control_6fa8fc4434',
                'placement' => 'content',
                'width' => '100',
                'hide_if_not_selected' => 'false',
                'required' => 'false',
                'translate' => 'false',
                'save_in_meta' => 'false',
                'save_in_meta_name' => '',
                'multiline' => 'false',
                'placeholder' => '',
                'characters_limit' => '',
            ),
        ),
        'code' => array(
            'output_method' => 'template',
            'editor_html' => '',
            'editor_callback' => '',
            'editor_css' => '',
            'frontend_html' => '',
            'frontend_callback' => '',
            'frontend_css' => '',
            'show_preview' => 'never',
            'single_output' => false,
        ),
        'styles' => array(
        ),
        'condition' => array(
        ),
    ) );
    
    lazyblocks()->add_block( array(
        'id' => 137,
        'title' => 'Gallery',
        'icon' => '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path d="M11.99 18.54l-7.37-5.73L3 14.07l9 7 9-7-1.63-1.27-7.38 5.74zM12 16l7.36-5.73L21 9l-9-7-9 7 1.63 1.27L12 16z" /></svg>',
        'keywords' => array(
        ),
        'slug' => 'lazyblock/gallery',
        'description' => '',
        'category' => 'lazyblocks',
        'category_label' => 'lazyblocks',
        'supports' => array(
            'customClassName' => true,
            'anchor' => true,
            'html' => false,
            'multiple' => true,
            'inserter' => true,
            'reusable' => true,
            'lock' => true,
            'align' => array(
            ),
        ),
        'ghostkit' => array(
            'supports' => array(
                'spacings' => false,
                'display' => false,
                'scrollReveal' => false,
                'frame' => false,
                'customCSS' => false,
            ),
        ),
        'controls' => array(
            'control_54ea3f4070' => array(
                'type' => 'rich_text',
                'name' => 'title',
                'default' => '',
                'label' => 'Title',
                'help' => '',
                'child_of' => '',
                'placement' => 'content',
                'width' => '100',
                'hide_if_not_selected' => 'false',
                'required' => 'false',
                'translate' => 'false',
                'save_in_meta' => 'false',
                'save_in_meta_name' => '',
                'multiline' => 'false',
                'placeholder' => '',
                'characters_limit' => '',
            ),
            'control_6fa8fc4434' => array(
                'type' => 'repeater',
                'name' => 'repeater',
                'default' => '',
                'label' => 'Repeater',
                'help' => '',
                'child_of' => '',
                'placement' => 'content',
                'width' => '100',
                'hide_if_not_selected' => 'false',
                'required' => 'false',
                'translate' => 'false',
                'save_in_meta' => 'false',
                'save_in_meta_name' => '',
                'rows_min' => '',
                'rows_max' => '',
                'rows_label' => '',
                'rows_add_button_label' => '',
                'rows_collapsible' => 'true',
                'rows_collapsed' => 'true',
                'placeholder' => '',
                'characters_limit' => '',
            ),
            'control_61cac74aff' => array(
                'type' => 'image',
                'name' => 'image',
                'default' => '',
                'label' => 'Image',
                'help' => '',
                'child_of' => 'control_6fa8fc4434',
                'placement' => 'content',
                'width' => '100',
                'hide_if_not_selected' => 'false',
                'required' => 'false',
                'translate' => 'false',
                'save_in_meta' => 'false',
                'save_in_meta_name' => '',
                'insert_from_url' => 'false',
                'preview_size' => 'medium',
                'placeholder' => '',
                'characters_limit' => '',
            ),
        ),
        'code' => array(
            'output_method' => 'template',
            'editor_html' => '',
            'editor_callback' => '',
            'editor_css' => '',
            'frontend_html' => '',
            'frontend_callback' => '',
            'frontend_css' => '',
            'show_preview' => 'never',
            'single_output' => false,
        ),
        'styles' => array(
        ),
        'condition' => array(
        ),
    ) );
    
    lazyblocks()->add_block( array(
        'id' => 136,
        'title' => 'Testimonials',
        'icon' => '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path d="M11.99 18.54l-7.37-5.73L3 14.07l9 7 9-7-1.63-1.27-7.38 5.74zM12 16l7.36-5.73L21 9l-9-7-9 7 1.63 1.27L12 16z" /></svg>',
        'keywords' => array(
        ),
        'slug' => 'lazyblock/testimonials',
        'description' => '',
        'category' => 'lazyblocks',
        'category_label' => 'lazyblocks',
        'supports' => array(
            'customClassName' => true,
            'anchor' => true,
            'html' => false,
            'multiple' => true,
            'inserter' => true,
            'reusable' => true,
            'lock' => true,
            'align' => array(
            ),
        ),
        'ghostkit' => array(
            'supports' => array(
                'spacings' => false,
                'display' => false,
                'scrollReveal' => false,
                'frame' => false,
                'customCSS' => false,
            ),
        ),
        'controls' => array(
            'control_54ea3f4070' => array(
                'type' => 'rich_text',
                'name' => 'title',
                'default' => '',
                'label' => 'Title',
                'help' => '',
                'child_of' => '',
                'placement' => 'content',
                'width' => '100',
                'hide_if_not_selected' => 'false',
                'required' => 'false',
                'translate' => 'false',
                'save_in_meta' => 'false',
                'save_in_meta_name' => '',
                'multiline' => 'false',
                'placeholder' => '',
                'characters_limit' => '',
            ),
            'control_6fa8fc4434' => array(
                'type' => 'repeater',
                'name' => 'repeater',
                'default' => '',
                'label' => 'Repeater',
                'help' => '',
                'child_of' => '',
                'placement' => 'content',
                'width' => '100',
                'hide_if_not_selected' => 'false',
                'required' => 'false',
                'translate' => 'false',
                'save_in_meta' => 'false',
                'save_in_meta_name' => '',
                'rows_min' => '',
                'rows_max' => '',
                'rows_label' => '',
                'rows_add_button_label' => '',
                'rows_collapsible' => 'true',
                'rows_collapsed' => 'true',
                'placeholder' => '',
                'characters_limit' => '',
            ),
            'control_61cac74aff' => array(
                'type' => 'rich_text',
                'name' => 'quote',
                'default' => '',
                'label' => 'Quote',
                'help' => '',
                'child_of' => 'control_6fa8fc4434',
                'placement' => 'content',
                'width' => '100',
                'hide_if_not_selected' => 'false',
                'required' => 'false',
                'translate' => 'false',
                'save_in_meta' => 'false',
                'save_in_meta_name' => '',
                'multiline' => 'false',
                'placeholder' => '',
                'characters_limit' => '',
            ),
            'control_3159c947af' => array(
                'type' => 'rich_text',
                'name' => 'author',
                'default' => '',
                'label' => 'Author',
                'help' => '',
                'child_of' => 'control_6fa8fc4434',
                'placement' => 'content',
                'width' => '100',
                'hide_if_not_selected' => 'false',
                'required' => 'false',
                'translate' => 'false',
                'save_in_meta' => 'false',
                'save_in_meta_name' => '',
                'multiline' => 'false',
                'placeholder' => '',
                'characters_limit' => '',
            ),
        ),
        'code' => array(
            'output_method' => 'template',
            'editor_html' => '',
            'editor_callback' => '',
            'editor_css' => '',
            'frontend_html' => '',
            'frontend_callback' => '',
            'frontend_css' => '',
            'show_preview' => 'never',
            'single_output' => false,
        ),
        'styles' => array(
        ),
        'condition' => array(
        ),
    ) );
    
    lazyblocks()->add_block( array(
        'id' => 135,
        'title' => 'Team',
        'icon' => '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path d="M11.99 18.54l-7.37-5.73L3 14.07l9 7 9-7-1.63-1.27-7.38 5.74zM12 16l7.36-5.73L21 9l-9-7-9 7 1.63 1.27L12 16z" /></svg>',
        'keywords' => array(
        ),
        'slug' => 'lazyblock/team',
        'description' => '',
        'category' => 'lazyblocks',
        'category_label' => 'lazyblocks',
        'supports' => array(
            'customClassName' => true,
            'anchor' => true,
            'html' => false,
            'multiple' => true,
            'inserter' => true,
            'reusable' => true,
            'lock' => true,
            'align' => array(
            ),
        ),
        'ghostkit' => array(
            'supports' => array(
                'spacings' => false,
                'display' => false,
                'scrollReveal' => false,
                'frame' => false,
                'customCSS' => false,
            ),
        ),
        'controls' => array(
            'control_54ea3f4070' => array(
                'type' => 'rich_text',
                'name' => 'title',
                'default' => '',
                'label' => 'Title',
                'help' => '',
                'child_of' => '',
                'placement' => 'content',
                'width' => '100',
                'hide_if_not_selected' => 'false',
                'required' => 'false',
                'translate' => 'false',
                'save_in_meta' => 'false',
                'save_in_meta_name' => '',
                'multiline' => 'false',
                'placeholder' => '',
                'characters_limit' => '',
            ),
            'control_6fa8fc4434' => array(
                'type' => 'repeater',
                'name' => 'repeater',
                'default' => '',
                'label' => 'Repeater',
                'help' => '',
                'child_of' => '',
                'placement' => 'content',
                'width' => '100',
                'hide_if_not_selected' => 'false',
                'required' => 'false',
                'translate' => 'false',
                'save_in_meta' => 'false',
                'save_in_meta_name' => '',
                'rows_min' => '',
                'rows_max' => '',
                'rows_label' => '',
                'rows_add_button_label' => '',
                'rows_collapsible' => 'true',
                'rows_collapsed' => 'true',
                'placeholder' => '',
                'characters_limit' => '',
            ),
            'control_61cac74aff' => array(
                'type' => 'image',
                'name' => 'image',
                'default' => '',
                'label' => 'Image',
                'help' => '',
                'child_of' => 'control_6fa8fc4434',
                'placement' => 'content',
                'width' => '100',
                'hide_if_not_selected' => 'false',
                'required' => 'false',
                'translate' => 'false',
                'save_in_meta' => 'false',
                'save_in_meta_name' => '',
                'insert_from_url' => 'false',
                'preview_size' => 'medium',
                'placeholder' => '',
                'characters_limit' => '',
            ),
            'control_d33b7a4f08' => array(
                'type' => 'rich_text',
                'name' => 'job',
                'default' => '',
                'label' => 'Job',
                'help' => '',
                'child_of' => 'control_6fa8fc4434',
                'placement' => 'content',
                'width' => '50',
                'hide_if_not_selected' => 'false',
                'required' => 'false',
                'translate' => 'false',
                'save_in_meta' => 'false',
                'save_in_meta_name' => '',
                'multiline' => 'false',
                'placeholder' => '',
                'characters_limit' => '',
            ),
            'control_8d0abe41fd' => array(
                'type' => 'rich_text',
                'name' => 'name',
                'default' => '',
                'label' => 'Name',
                'help' => '',
                'child_of' => 'control_6fa8fc4434',
                'placement' => 'content',
                'width' => '50',
                'hide_if_not_selected' => 'false',
                'required' => 'false',
                'translate' => 'false',
                'save_in_meta' => 'false',
                'save_in_meta_name' => '',
                'multiline' => 'false',
                'placeholder' => '',
                'characters_limit' => '',
            ),
            'control_b308bc4e4a' => array(
                'type' => 'rich_text',
                'name' => 'description',
                'default' => '',
                'label' => 'Description',
                'help' => '',
                'child_of' => 'control_6fa8fc4434',
                'placement' => 'content',
                'width' => '100',
                'hide_if_not_selected' => 'false',
                'required' => 'false',
                'translate' => 'false',
                'save_in_meta' => 'false',
                'save_in_meta_name' => '',
                'multiline' => 'false',
                'placeholder' => '',
                'characters_limit' => '',
            ),
            'control_383a9c4b54' => array(
                'type' => 'url',
                'name' => 'link-linkedin',
                'default' => '',
                'label' => 'Link LinkedIn',
                'help' => '',
                'child_of' => 'control_6fa8fc4434',
                'placement' => 'content',
                'width' => '50',
                'hide_if_not_selected' => 'false',
                'required' => 'false',
                'translate' => 'false',
                'save_in_meta' => 'false',
                'save_in_meta_name' => '',
                'placeholder' => '',
                'characters_limit' => '',
            ),
            'control_1b189a4126' => array(
                'type' => 'rich_text',
                'name' => 'account-name-of-linkedin',
                'default' => '',
                'label' => 'Account name of LinkedIn',
                'help' => '',
                'child_of' => 'control_6fa8fc4434',
                'placement' => 'content',
                'width' => '50',
                'hide_if_not_selected' => 'false',
                'required' => 'false',
                'translate' => 'false',
                'save_in_meta' => 'false',
                'save_in_meta_name' => '',
                'multiline' => 'false',
                'placeholder' => '',
                'characters_limit' => '',
            ),
            'control_730ad543f3' => array(
                'type' => 'url',
                'name' => 'link-twitter',
                'default' => '',
                'label' => 'Link Twitter',
                'help' => '',
                'child_of' => 'control_6fa8fc4434',
                'placement' => 'content',
                'width' => '50',
                'hide_if_not_selected' => 'false',
                'required' => 'false',
                'translate' => 'false',
                'save_in_meta' => 'false',
                'save_in_meta_name' => '',
                'placeholder' => '',
                'characters_limit' => '',
            ),
            'control_a1586d45e2' => array(
                'type' => 'rich_text',
                'name' => 'account-name-of-twitter',
                'default' => '',
                'label' => 'Account name of Twitter',
                'help' => '',
                'child_of' => 'control_6fa8fc4434',
                'placement' => 'content',
                'width' => '50',
                'hide_if_not_selected' => 'false',
                'required' => 'false',
                'translate' => 'false',
                'save_in_meta' => 'false',
                'save_in_meta_name' => '',
                'multiline' => 'false',
                'placeholder' => '',
                'characters_limit' => '',
            ),
            'control_56ea1a4ae2' => array(
                'type' => 'url',
                'name' => 'link-instagram',
                'default' => '',
                'label' => 'Link Instagram',
                'help' => '',
                'child_of' => 'control_6fa8fc4434',
                'placement' => 'content',
                'width' => '50',
                'hide_if_not_selected' => 'false',
                'required' => 'false',
                'translate' => 'false',
                'save_in_meta' => 'false',
                'save_in_meta_name' => '',
                'placeholder' => '',
                'characters_limit' => '',
            ),
            'control_f25a214b2f' => array(
                'type' => 'rich_text',
                'name' => 'account-name-of-instagram',
                'default' => '',
                'label' => 'Account name of Instagram',
                'help' => '',
                'child_of' => 'control_6fa8fc4434',
                'placement' => 'content',
                'width' => '50',
                'hide_if_not_selected' => 'false',
                'required' => 'false',
                'translate' => 'false',
                'save_in_meta' => 'false',
                'save_in_meta_name' => '',
                'multiline' => 'false',
                'placeholder' => '',
                'characters_limit' => '',
            ),
            'control_d38ab64a60' => array(
                'type' => 'url',
                'name' => 'link-facebook',
                'default' => '',
                'label' => 'Link Facebook',
                'help' => '',
                'child_of' => 'control_6fa8fc4434',
                'placement' => 'content',
                'width' => '50',
                'hide_if_not_selected' => 'false',
                'required' => 'false',
                'translate' => 'false',
                'save_in_meta' => 'false',
                'save_in_meta_name' => '',
                'placeholder' => '',
                'characters_limit' => '',
            ),
            'control_6ff97d4923' => array(
                'type' => 'rich_text',
                'name' => 'account-name-of-facebook',
                'default' => '',
                'label' => 'Account name of Facebook',
                'help' => '',
                'child_of' => 'control_6fa8fc4434',
                'placement' => 'content',
                'width' => '50',
                'hide_if_not_selected' => 'false',
                'required' => 'false',
                'translate' => 'false',
                'save_in_meta' => 'false',
                'save_in_meta_name' => '',
                'multiline' => 'false',
                'placeholder' => '',
                'characters_limit' => '',
            ),
        ),
        'code' => array(
            'output_method' => 'template',
            'editor_html' => '',
            'editor_callback' => '',
            'editor_css' => '',
            'frontend_html' => '',
            'frontend_callback' => '',
            'frontend_css' => '',
            'show_preview' => 'never',
            'single_output' => false,
        ),
        'styles' => array(
        ),
        'condition' => array(
        ),
    ) );
    
    lazyblocks()->add_block( array(
        'id' => 134,
        'title' => 'Hero (pages)',
        'icon' => '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path d="M11.99 18.54l-7.37-5.73L3 14.07l9 7 9-7-1.63-1.27-7.38 5.74zM12 16l7.36-5.73L21 9l-9-7-9 7 1.63 1.27L12 16z" /></svg>',
        'keywords' => array(
        ),
        'slug' => 'lazyblock/hero-pages',
        'description' => '',
        'category' => 'lazyblocks',
        'category_label' => 'lazyblocks',
        'supports' => array(
            'customClassName' => true,
            'anchor' => true,
            'html' => false,
            'multiple' => true,
            'inserter' => true,
            'reusable' => true,
            'lock' => true,
            'align' => array(
            ),
        ),
        'ghostkit' => array(
            'supports' => array(
                'spacings' => false,
                'display' => false,
                'scrollReveal' => false,
                'frame' => false,
                'customCSS' => false,
            ),
        ),
        'controls' => array(
            'control_54ea3f4070' => array(
                'type' => 'rich_text',
                'name' => 'title',
                'default' => '',
                'label' => 'Title',
                'help' => '',
                'child_of' => '',
                'placement' => 'content',
                'width' => '100',
                'hide_if_not_selected' => 'false',
                'required' => 'false',
                'translate' => 'false',
                'save_in_meta' => 'false',
                'save_in_meta_name' => '',
                'multiline' => 'false',
                'placeholder' => '',
                'characters_limit' => '',
            ),
        ),
        'code' => array(
            'output_method' => 'template',
            'editor_html' => '',
            'editor_callback' => '',
            'editor_css' => '',
            'frontend_html' => '',
            'frontend_callback' => '',
            'frontend_css' => '',
            'show_preview' => 'never',
            'single_output' => false,
        ),
        'styles' => array(
        ),
        'condition' => array(
        ),
    ) );
    
    lazyblocks()->add_block( array(
        'id' => 133,
        'title' => 'Partners',
        'icon' => '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path d="M11.99 18.54l-7.37-5.73L3 14.07l9 7 9-7-1.63-1.27-7.38 5.74zM12 16l7.36-5.73L21 9l-9-7-9 7 1.63 1.27L12 16z" /></svg>',
        'keywords' => array(
        ),
        'slug' => 'lazyblock/partners',
        'description' => '',
        'category' => 'lazyblocks',
        'category_label' => 'lazyblocks',
        'supports' => array(
            'customClassName' => true,
            'anchor' => true,
            'html' => false,
            'multiple' => true,
            'inserter' => true,
            'reusable' => true,
            'lock' => true,
            'align' => array(
            ),
        ),
        'ghostkit' => array(
            'supports' => array(
                'spacings' => false,
                'display' => false,
                'scrollReveal' => false,
                'frame' => false,
                'customCSS' => false,
            ),
        ),
        'controls' => array(
            'control_54ea3f4070' => array(
                'type' => 'rich_text',
                'name' => 'title',
                'default' => '',
                'label' => 'Title',
                'help' => '',
                'child_of' => '',
                'placement' => 'content',
                'width' => '100',
                'hide_if_not_selected' => 'false',
                'required' => 'false',
                'translate' => 'false',
                'save_in_meta' => 'false',
                'save_in_meta_name' => '',
                'multiline' => 'false',
                'placeholder' => '',
                'characters_limit' => '',
            ),
            'control_6fa8fc4434' => array(
                'type' => 'repeater',
                'name' => 'repeater',
                'default' => '',
                'label' => 'Repeater',
                'help' => '',
                'child_of' => '',
                'placement' => 'content',
                'width' => '100',
                'hide_if_not_selected' => 'false',
                'required' => 'false',
                'translate' => 'false',
                'save_in_meta' => 'false',
                'save_in_meta_name' => '',
                'rows_min' => '',
                'rows_max' => '',
                'rows_label' => '',
                'rows_add_button_label' => '',
                'rows_collapsible' => 'true',
                'rows_collapsed' => 'true',
                'placeholder' => '',
                'characters_limit' => '',
            ),
            'control_61cac74aff' => array(
                'type' => 'image',
                'name' => 'logo',
                'default' => '',
                'label' => 'Logo',
                'help' => '',
                'child_of' => 'control_6fa8fc4434',
                'placement' => 'content',
                'width' => '100',
                'hide_if_not_selected' => 'false',
                'required' => 'false',
                'translate' => 'false',
                'save_in_meta' => 'false',
                'save_in_meta_name' => '',
                'insert_from_url' => 'false',
                'preview_size' => 'medium',
                'placeholder' => '',
                'characters_limit' => '',
            ),
        ),
        'code' => array(
            'output_method' => 'template',
            'editor_html' => '',
            'editor_callback' => '',
            'editor_css' => '',
            'frontend_html' => '',
            'frontend_callback' => '',
            'frontend_css' => '',
            'show_preview' => 'never',
            'single_output' => false,
        ),
        'styles' => array(
        ),
        'condition' => array(
        ),
    ) );
    
    lazyblocks()->add_block( array(
        'id' => 132,
        'title' => 'Places',
        'icon' => '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path d="M11.99 18.54l-7.37-5.73L3 14.07l9 7 9-7-1.63-1.27-7.38 5.74zM12 16l7.36-5.73L21 9l-9-7-9 7 1.63 1.27L12 16z" /></svg>',
        'keywords' => array(
        ),
        'slug' => 'lazyblock/places',
        'description' => '',
        'category' => 'lazyblocks',
        'category_label' => 'lazyblocks',
        'supports' => array(
            'customClassName' => true,
            'anchor' => true,
            'html' => false,
            'multiple' => true,
            'inserter' => true,
            'reusable' => true,
            'lock' => true,
            'align' => array(
            ),
        ),
        'ghostkit' => array(
            'supports' => array(
                'spacings' => false,
                'display' => false,
                'scrollReveal' => false,
                'frame' => false,
                'customCSS' => false,
            ),
        ),
        'controls' => array(
            'control_6fa8fc4434' => array(
                'type' => 'repeater',
                'name' => 'repeater',
                'default' => '',
                'label' => 'Repeater',
                'help' => '',
                'child_of' => '',
                'placement' => 'content',
                'width' => '100',
                'hide_if_not_selected' => 'false',
                'required' => 'false',
                'translate' => 'false',
                'save_in_meta' => 'false',
                'save_in_meta_name' => '',
                'rows_min' => '',
                'rows_max' => '',
                'rows_label' => '',
                'rows_add_button_label' => '',
                'rows_collapsible' => 'true',
                'rows_collapsed' => 'true',
                'placeholder' => '',
                'characters_limit' => '',
            ),
            'control_61cac74aff' => array(
                'type' => 'rich_text',
                'name' => 'city',
                'default' => '',
                'label' => 'City',
                'help' => '',
                'child_of' => 'control_6fa8fc4434',
                'placement' => 'content',
                'width' => '50',
                'hide_if_not_selected' => 'false',
                'required' => 'false',
                'translate' => 'false',
                'save_in_meta' => 'false',
                'save_in_meta_name' => '',
                'multiline' => 'false',
                'placeholder' => '',
                'characters_limit' => '',
            ),
            'control_fe59d6415b' => array(
                'type' => 'rich_text',
                'name' => 'adress',
                'default' => '',
                'label' => 'Adress',
                'help' => '',
                'child_of' => 'control_6fa8fc4434',
                'placement' => 'content',
                'width' => '50',
                'hide_if_not_selected' => 'false',
                'required' => 'false',
                'translate' => 'false',
                'save_in_meta' => 'false',
                'save_in_meta_name' => '',
                'multiline' => 'false',
                'placeholder' => '',
                'characters_limit' => '',
            ),
            'control_ab3b5841ce' => array(
                'type' => 'rich_text',
                'name' => 'phone',
                'default' => '',
                'label' => 'Phone',
                'help' => '',
                'child_of' => 'control_6fa8fc4434',
                'placement' => 'content',
                'width' => '50',
                'hide_if_not_selected' => 'false',
                'required' => 'false',
                'translate' => 'false',
                'save_in_meta' => 'false',
                'save_in_meta_name' => '',
                'multiline' => 'false',
                'placeholder' => '',
                'characters_limit' => '',
            ),
            'control_b22ac64a7c' => array(
                'type' => 'rich_text',
                'name' => 'email',
                'default' => '',
                'label' => 'Email',
                'help' => '',
                'child_of' => 'control_6fa8fc4434',
                'placement' => 'content',
                'width' => '50',
                'hide_if_not_selected' => 'false',
                'required' => 'false',
                'translate' => 'false',
                'save_in_meta' => 'false',
                'save_in_meta_name' => '',
                'multiline' => 'false',
                'placeholder' => '',
                'characters_limit' => '',
            ),
        ),
        'code' => array(
            'output_method' => 'template',
            'editor_html' => '',
            'editor_callback' => '',
            'editor_css' => '',
            'frontend_html' => '',
            'frontend_callback' => '',
            'frontend_css' => '',
            'show_preview' => 'never',
            'single_output' => false,
        ),
        'styles' => array(
        ),
        'condition' => array(
        ),
    ) );
    
    lazyblocks()->add_block( array(
        'id' => 131,
        'title' => 'Contact',
        'icon' => '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path d="M11.99 18.54l-7.37-5.73L3 14.07l9 7 9-7-1.63-1.27-7.38 5.74zM12 16l7.36-5.73L21 9l-9-7-9 7 1.63 1.27L12 16z" /></svg>',
        'keywords' => array(
        ),
        'slug' => 'lazyblock/contact',
        'description' => '',
        'category' => 'lazyblocks',
        'category_label' => 'lazyblocks',
        'supports' => array(
            'customClassName' => true,
            'anchor' => true,
            'html' => false,
            'multiple' => true,
            'inserter' => true,
            'reusable' => true,
            'lock' => true,
            'align' => array(
            ),
        ),
        'ghostkit' => array(
            'supports' => array(
                'spacings' => false,
                'display' => false,
                'scrollReveal' => false,
                'frame' => false,
                'customCSS' => false,
            ),
        ),
        'controls' => array(
            'control_61cac74aff' => array(
                'type' => 'rich_text',
                'name' => 'city',
                'default' => '',
                'label' => 'City',
                'help' => '',
                'child_of' => 'control_6fa8fc4434',
                'placement' => 'content',
                'width' => '50',
                'hide_if_not_selected' => 'false',
                'required' => 'false',
                'translate' => 'false',
                'save_in_meta' => 'false',
                'save_in_meta_name' => '',
                'multiline' => 'false',
                'placeholder' => '',
                'characters_limit' => '',
            ),
            'control_fe59d6415b' => array(
                'type' => 'rich_text',
                'name' => 'adress',
                'default' => '',
                'label' => 'Adress',
                'help' => '',
                'child_of' => 'control_6fa8fc4434',
                'placement' => 'content',
                'width' => '50',
                'hide_if_not_selected' => 'false',
                'required' => 'false',
                'translate' => 'false',
                'save_in_meta' => 'false',
                'save_in_meta_name' => '',
                'multiline' => 'false',
                'placeholder' => '',
                'characters_limit' => '',
            ),
            'control_ab3b5841ce' => array(
                'type' => 'rich_text',
                'name' => 'phone',
                'default' => '',
                'label' => 'Phone',
                'help' => '',
                'child_of' => 'control_6fa8fc4434',
                'placement' => 'content',
                'width' => '50',
                'hide_if_not_selected' => 'false',
                'required' => 'false',
                'translate' => 'false',
                'save_in_meta' => 'false',
                'save_in_meta_name' => '',
                'multiline' => 'false',
                'placeholder' => '',
                'characters_limit' => '',
            ),
            'control_b22ac64a7c' => array(
                'type' => 'rich_text',
                'name' => 'email',
                'default' => '',
                'label' => 'Email',
                'help' => '',
                'child_of' => 'control_6fa8fc4434',
                'placement' => 'content',
                'width' => '50',
                'hide_if_not_selected' => 'false',
                'required' => 'false',
                'translate' => 'false',
                'save_in_meta' => 'false',
                'save_in_meta_name' => '',
                'multiline' => 'false',
                'placeholder' => '',
                'characters_limit' => '',
            ),
            'control_fa9b40469c' => array(
                'type' => 'text',
                'name' => 'shortcode-form',
                'default' => '',
                'label' => 'Shortcode form',
                'help' => '',
                'child_of' => '',
                'placement' => 'content',
                'width' => '100',
                'hide_if_not_selected' => 'false',
                'required' => 'false',
                'translate' => 'false',
                'save_in_meta' => 'false',
                'save_in_meta_name' => '',
                'placeholder' => '',
                'characters_limit' => '',
            ),
        ),
        'code' => array(
            'output_method' => 'template',
            'editor_html' => '',
            'editor_callback' => '',
            'editor_css' => '',
            'frontend_html' => '',
            'frontend_callback' => '',
            'frontend_css' => '',
            'show_preview' => 'never',
            'single_output' => false,
        ),
        'styles' => array(
        ),
        'condition' => array(
        ),
    ) );
    
    lazyblocks()->add_block( array(
        'id' => 130,
        'title' => 'Content',
        'icon' => '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path d="M11.99 18.54l-7.37-5.73L3 14.07l9 7 9-7-1.63-1.27-7.38 5.74zM12 16l7.36-5.73L21 9l-9-7-9 7 1.63 1.27L12 16z" /></svg>',
        'keywords' => array(
        ),
        'slug' => 'lazyblock/content',
        'description' => '',
        'category' => 'lazyblocks',
        'category_label' => 'lazyblocks',
        'supports' => array(
            'customClassName' => true,
            'anchor' => true,
            'html' => false,
            'multiple' => true,
            'inserter' => true,
            'reusable' => true,
            'lock' => true,
            'align' => array(
            ),
        ),
        'ghostkit' => array(
            'supports' => array(
                'spacings' => false,
                'display' => false,
                'scrollReveal' => false,
                'frame' => false,
                'customCSS' => false,
            ),
        ),
        'controls' => array(
            'control_61cac74aff' => array(
                'type' => 'rich_text',
                'name' => 'city',
                'default' => '',
                'label' => 'City',
                'help' => '',
                'child_of' => 'control_6fa8fc4434',
                'placement' => 'content',
                'width' => '50',
                'hide_if_not_selected' => 'false',
                'required' => 'false',
                'translate' => 'false',
                'save_in_meta' => 'false',
                'save_in_meta_name' => '',
                'multiline' => 'false',
                'placeholder' => '',
                'characters_limit' => '',
            ),
            'control_fe59d6415b' => array(
                'type' => 'rich_text',
                'name' => 'adress',
                'default' => '',
                'label' => 'Adress',
                'help' => '',
                'child_of' => 'control_6fa8fc4434',
                'placement' => 'content',
                'width' => '50',
                'hide_if_not_selected' => 'false',
                'required' => 'false',
                'translate' => 'false',
                'save_in_meta' => 'false',
                'save_in_meta_name' => '',
                'multiline' => 'false',
                'placeholder' => '',
                'characters_limit' => '',
            ),
            'control_ab3b5841ce' => array(
                'type' => 'rich_text',
                'name' => 'phone',
                'default' => '',
                'label' => 'Phone',
                'help' => '',
                'child_of' => 'control_6fa8fc4434',
                'placement' => 'content',
                'width' => '50',
                'hide_if_not_selected' => 'false',
                'required' => 'false',
                'translate' => 'false',
                'save_in_meta' => 'false',
                'save_in_meta_name' => '',
                'multiline' => 'false',
                'placeholder' => '',
                'characters_limit' => '',
            ),
            'control_b22ac64a7c' => array(
                'type' => 'rich_text',
                'name' => 'email',
                'default' => '',
                'label' => 'Email',
                'help' => '',
                'child_of' => 'control_6fa8fc4434',
                'placement' => 'content',
                'width' => '50',
                'hide_if_not_selected' => 'false',
                'required' => 'false',
                'translate' => 'false',
                'save_in_meta' => 'false',
                'save_in_meta_name' => '',
                'multiline' => 'false',
                'placeholder' => '',
                'characters_limit' => '',
            ),
            'control_aa299b456f' => array(
                'type' => 'classic_editor',
                'name' => 'content',
                'default' => '',
                'label' => 'Content',
                'help' => '',
                'child_of' => '',
                'placement' => 'content',
                'width' => '100',
                'hide_if_not_selected' => 'false',
                'required' => 'false',
                'translate' => 'false',
                'save_in_meta' => 'false',
                'save_in_meta_name' => '',
                'placeholder' => '',
                'characters_limit' => '',
            ),
        ),
        'code' => array(
            'output_method' => 'template',
            'editor_html' => '',
            'editor_callback' => '',
            'editor_css' => '',
            'frontend_html' => '',
            'frontend_callback' => '',
            'frontend_css' => '',
            'show_preview' => 'never',
            'single_output' => false,
        ),
        'styles' => array(
        ),
        'condition' => array(
        ),
    ) );
    
    lazyblocks()->add_block( array(
        'id' => 129,
        'title' => 'Blog',
        'icon' => '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path d="M11.99 18.54l-7.37-5.73L3 14.07l9 7 9-7-1.63-1.27-7.38 5.74zM12 16l7.36-5.73L21 9l-9-7-9 7 1.63 1.27L12 16z" /></svg>',
        'keywords' => array(
        ),
        'slug' => 'lazyblock/blog',
        'description' => '',
        'category' => 'lazyblocks',
        'category_label' => 'lazyblocks',
        'supports' => array(
            'customClassName' => true,
            'anchor' => true,
            'html' => false,
            'multiple' => true,
            'inserter' => true,
            'reusable' => true,
            'lock' => true,
            'align' => array(
            ),
        ),
        'ghostkit' => array(
            'supports' => array(
                'spacings' => false,
                'display' => false,
                'scrollReveal' => false,
                'frame' => false,
                'customCSS' => false,
            ),
        ),
        'controls' => array(
            'control_61cac74aff' => array(
                'type' => 'rich_text',
                'name' => 'city',
                'default' => '',
                'label' => 'City',
                'help' => '',
                'child_of' => 'control_6fa8fc4434',
                'placement' => 'content',
                'width' => '50',
                'hide_if_not_selected' => 'false',
                'required' => 'false',
                'translate' => 'false',
                'save_in_meta' => 'false',
                'save_in_meta_name' => '',
                'multiline' => 'false',
                'placeholder' => '',
                'characters_limit' => '',
            ),
            'control_fe59d6415b' => array(
                'type' => 'rich_text',
                'name' => 'adress',
                'default' => '',
                'label' => 'Adress',
                'help' => '',
                'child_of' => 'control_6fa8fc4434',
                'placement' => 'content',
                'width' => '50',
                'hide_if_not_selected' => 'false',
                'required' => 'false',
                'translate' => 'false',
                'save_in_meta' => 'false',
                'save_in_meta_name' => '',
                'multiline' => 'false',
                'placeholder' => '',
                'characters_limit' => '',
            ),
            'control_ab3b5841ce' => array(
                'type' => 'rich_text',
                'name' => 'phone',
                'default' => '',
                'label' => 'Phone',
                'help' => '',
                'child_of' => 'control_6fa8fc4434',
                'placement' => 'content',
                'width' => '50',
                'hide_if_not_selected' => 'false',
                'required' => 'false',
                'translate' => 'false',
                'save_in_meta' => 'false',
                'save_in_meta_name' => '',
                'multiline' => 'false',
                'placeholder' => '',
                'characters_limit' => '',
            ),
            'control_b22ac64a7c' => array(
                'type' => 'rich_text',
                'name' => 'email',
                'default' => '',
                'label' => 'Email',
                'help' => '',
                'child_of' => 'control_6fa8fc4434',
                'placement' => 'content',
                'width' => '50',
                'hide_if_not_selected' => 'false',
                'required' => 'false',
                'translate' => 'false',
                'save_in_meta' => 'false',
                'save_in_meta_name' => '',
                'multiline' => 'false',
                'placeholder' => '',
                'characters_limit' => '',
            ),
        ),
        'code' => array(
            'output_method' => 'template',
            'editor_html' => '',
            'editor_callback' => '',
            'editor_css' => '',
            'frontend_html' => '',
            'frontend_callback' => '',
            'frontend_css' => '',
            'show_preview' => 'never',
            'single_output' => false,
        ),
        'styles' => array(
        ),
        'condition' => array(
        ),
    ) );
    
} );